Draft use case model
Huy-Ngo/gpms pull request #12
Opened 2020-11-13 02:53 UTC by 9a24f0

Resolve GH-1, atm, only use cases related to project is drafted

2020-11-13 03:59 UTC, McSinyx reviewed
Some early nits.

2020-11-13 03:59 UTC, McSinyx commented on docs/source/requirements/use-case-model.rst
> +	Staff --> Logout
```suggestion
   Staff --> Search
   Staff --> Export
   Staff --> Report
   Staff --> Login
   Staff --> Register
   Staff --> Logout
```

2020-11-13 03:59 UTC, McSinyx commented on docs/source/requirements/use-case-model.rst
> +   Student --> Complete
Should Lecturer be able to do this?

2020-11-13 03:59 UTC, McSinyx commented on docs/source/requirements/use-case-model.rst
> +   usecase "Maintain system" as Maintain
What does this mean?

2020-11-13 03:59 UTC, McSinyx commented on docs/source/requirements/use-case-model.rst
> +------------
Since this file is gonna be super long, I suggest double newline between use cases.

```suggestion


Join Project
------------
```

2020-11-13 04:03 UTC, 9a24f0 commented on docs/source/requirements/use-case-model.rst
> +   Student --> Complete
I let Lecturer to inherits from Student for better visual experience of the diagram only )-:
Lecturer should not inherit "Complete" from Student.

2020-11-13 04:11 UTC, Huy-Ngo commented on docs/source/requirements/use-case-model.rst
> +	Staff --> Logout
I personally prefer tabs over spaces for [accessibility](https://dev.to/alexandersandberg/why-we-should-default-to-tabs-instead-of-spaces-for-an-accessible-first-environment-101f).

2020-11-13 04:22 UTC, 9a24f0 commented on docs/source/requirements/use-case-model.rst
> +   usecase "Maintain system" as Maintain
I took the example as we did in OOAD course, here is the [link](https://www.freeprojectz.com/uml-diagram/farm-management-system-uml-diagram). From what I understand, admin should be able to access to every system within use cases and also maintain and manage the system.

2020-11-13 04:23 UTC, McSinyx commented on docs/source/requirements/use-case-model.rst
> +	Staff --> Logout
reST specs especially requires space alignment, e.g.

```rst
#. foo
   bar
```

and

```rst
* blah
  blah
```

Also whoever said tab width is not 8 should not ever be allowed to develop anything having to do with plaintext operations and stdio.  Setting tabs to anything other than 8 is basically putting developer/writter first, user/reader second and what I (as an user coming from unix-like systems with grep, less, etc.) would consider a dick move.

2020-11-13 04:24 UTC, 9a24f0 commented on docs/source/requirements/use-case-model.rst
> +	Staff --> Logout
@McSinyx language!

2020-11-13 05:00 UTC, McSinyx commented on docs/source/requirements/use-case-model.rst
> +	Staff --> Logout
Emotions aside, to be clear [I'm nothing against using tabs for *indentation*](https://git.sr.ht/~cnx/dotfiles/tree/5b07539fad29d4f88662c9c3e2f602860b3663be/vim/.vim/vimrc#L23).  In other words, it'd be perfectly fine for me to read

```rst
.. uml::

   class Foo {
   	bar
   }
```

2020-11-13 05:01 UTC, McSinyx commented on docs/source/requirements/use-case-model.rst
> +   Student --> Complete
Create a base *Collaborator* actor or something then.

2020-11-13 05:13 UTC, Huy-Ngo commented on docs/source/requirements/use-case-model.rst
> +   Student --> Complete
Neither lecturer nor student should inherit from each other.

2020-11-13 05:19 UTC, Huy-Ngo requested changes

2020-11-13 05:19 UTC, Huy-Ngo commented on docs/source/requirements/use-case-model.rst
> +   Admin <|-- Staff
You are having the arrows in the opposite directions. Arrows should be from the subclass to the superclass. Also, I'm against the idea that Lecturer inherits Student.

2020-11-13 05:42 UTC, Huy-Ngo commented on docs/source/requirements/use-case-model.rst
> +   Admin <|-- Staff
You can move the Lecturer actor to the left to avoid messy arrows. Also, you can merge authentication use cases, I think. 

```plantuml
   left to right direction
   actor Student
   actor Staff
   actor Admin
   actor Lecturer

   usecase "Create project" as CreateP
   usecase "Join project" as JoinP
   usecase "Create tasks" as CreateT
   usecase "Join tasks" as JoinT
   usecase "Complete tasks" as Complete
   usecase "View results" as View
   usecase Evaluate
   usecase "Send message" as Msg

   usecase Search
   usecase "Search student" as s_stud
   usecase "Search lecturer" as s_lect
   usecase "Search project" as s_proj

   usecase Authentication as auth
   usecase Register
   usecase Login
   usecase Logout

   usecase "Make Report" as Report
   usecase "Export transcript" as Export

   usecase "Maintain system" as Maintain

   Staff --> Search
   Staff --> Export
   Staff --> Report
   Staff --> auth

   Student --> Search
   Student --> CreateP
   Student --> CreateT
   Student --> JoinP
   Student --> JoinT
   Student --> Complete
   Student --> Msg
   Student --> auth
   
   Search <-- Lecturer
   CreateP <-- Lecturer
   JoinP <-- Lecturer
   Msg <-- Lecturer
   auth <-- Lecturer

   Lecturer --> View
   Lecturer --> Evaluate

   Admin --> Maintain

   Admin <|-- Staff
   
   Search <.. s_stud: <<extends>>
   Search <.. s_lect: <<extends>>
   Search <.. s_proj: <<extends>>
   
   Register ..> auth : <<extends>>
   Login ..> auth : <<extends>>
   Logout ..> auth : <<extends>>
```

2020-11-13 05:43 UTC, Huy-Ngo commented on docs/source/requirements/use-case-model.rst
> +   Admin <|-- Staff
Admin can *possibly* be removed if the actor use all use cases, I believe.

2020-11-13 07:00 UTC, 9a24f0 commented on docs/source/requirements/use-case-model.rst
> +   Admin <|-- Staff
We need some recommendation on excluding _Admin_ actor, @McSinyx and @Yus147 have any idea?

2020-11-13 08:49 UTC, McSinyx commented on docs/source/requirements/use-case-model.rst
> +   Student --> Complete
Not from each other, but probably from the same base?

2020-11-13 08:51 UTC, McSinyx commented on docs/source/requirements/use-case-model.rst
> +   Admin <|-- Staff
I don't think the admins use all use cases, however, e.g. `Admin --> Evaluate` really sounds like corruption.

2020-11-13 12:26 UTC, Huy-Ngo commented on docs/source/requirements/use-case-model.rst
> +   Admin <|-- Staff
Lol ok, I agree

2020-11-15 13:24 UTC, Huy-Ngo requested changes

2020-11-15 13:24 UTC, Huy-Ngo commented on docs/source/requirements/use-case-model.rst
> +5. User 2 comments on the thread for discussion.
I think we should probably say "discussion thread" to avoid confusion with thread like the computer thing.

2020-11-15 13:24 UTC, Huy-Ngo commented on docs/source/requirements/use-case-model.rst
> +Send Message
As we model discussion as posts, I think "Create Discussion" and "Add comment" would be more appropriate use cases.

2020-11-15 13:24 UTC, Huy-Ngo commented on docs/source/requirements/use-case-model.rst
> +5. Staff download the file for printing purpose later.
Nitpick: pay attention to verb conjugation.

2020-11-15 13:24 UTC, Huy-Ngo commented on docs/source/requirements/use-case-model.rst
> +5. Staff download the file for printing purpose later.
You forgot to conjugate in several other use cases too.

2020-11-15 13:24 UTC, Huy-Ngo commented on docs/source/requirements/use-case-model.rst
> +
How about password change?

2020-11-15 13:24 UTC, Huy-Ngo commented on docs/source/requirements/use-case-model.rst
> +
Is the system really unchanged, though? It does change: the assignee of the task is set as the user. You also need to change this for other use cases.

2020-11-15 13:49 UTC, 9a24f0 commented on docs/source/requirements/use-case-model.rst
> +
I'm a bit confused with "system state" thinggy, gonna review it on a commit later.

2020-11-15 14:32 UTC, McSinyx commented on docs/source/requirements/use-case-model.rst
> +5. User 2 comments on the thread for discussion.
Unrelated, but what is User?  Since it seems to only refer to either Student or Lecturer, I (once again) suggest

```plantuml
Student --|> Collaborator
Lecturer --|> Collaborator
```

2020-11-15 16:47 UTC, 9a24f0 commented on docs/source/requirements/use-case-model.rst
> +5. User 2 comments on the thread for discussion.
User refer to either Student or Lecturer, but I'm against the idea of making another actor

2020-11-15 23:59 UTC, Huy-Ngo commented on docs/source/requirements/use-case-model.rst
> +matching student.
These look like extra work for you but ok.

2020-11-16 00:01 UTC, Huy-Ngo commented on docs/source/requirements/use-case-model.rst
> +5. User verify by his/her provided email.
Speaking of email, I wonder if we can use school's mail system or we have to do it on our own. Off topic tho

2020-11-16 08:01 UTC, 9a24f0 commented on docs/source/requirements/use-case-model.rst
> +5. User verify by his/her provided email.
We will also look on this later on.

2020-11-16 08:04 UTC, 9a24f0 commented on docs/source/requirements/use-case-model.rst
> +
We will look on this later on.

2020-11-16 15:03 UTC, DDHLong approved these changes

2020-11-16 15:20 UTC, McSinyx approved these changes
The diagram LGTM, and I trust you on the descriptions.  We can iterate on this as we go, let's not make perfect the enemy of good.

2020-11-17 02:23 UTC, Huy-Ngo approved these changes

2020-11-17 02:24 UTC, merged