Create a draft for the database design
Huy-Ngo/gpms pull request #13
Opened 2020-11-13 06:42 UTC by Huy-Ngo

I have created a draft design for the database of this system. As it is not complete yet, please comment on how you would want to change it.

After merged this PR will resolve #2

2020-11-13 06:52 UTC, Huy-Ngo commented
I'm considering adding more redundancy into the database since NoSQL is about denormalization.

2020-11-15 07:48 UTC, McSinyx requested changes
This is document is orphaned I think, please link to it in `solution/index`.

2020-11-15 07:48 UTC, McSinyx commented on docs/source/solution/database.rst
> +      "username": "Foo Bar",
Let's use `username` (unique) and `name` here.

2020-11-15 07:48 UTC, McSinyx commented on docs/source/solution/database.rst
> +      "project-name": "Project Name",
Nit: I find the `project-` (also `task-`, `thread-` and `comment-`) part redundant.

2020-11-15 07:48 UTC, McSinyx commented on docs/source/solution/database.rst
> +      "created-on": "(date time in ISO 8601 format)"
Missing comma.

2020-11-15 07:48 UTC, McSinyx commented on docs/source/solution/database.rst
> +      "discussion-threads": [
Would putin `discussion` in each task be more intuitive?

2020-11-15 13:01 UTC, Huy-Ngo commented on docs/source/solution/database.rst
> +      "username": "Foo Bar",
Why should username be unique? For sign in? We can use email for login if that's the case.

2020-11-15 13:04 UTC, Huy-Ngo commented on docs/source/solution/database.rst
> +      "discussion-threads": [
There can be discussion before any tasks is created, but sure, assigning to task is more useful.

2020-11-15 13:05 UTC, McSinyx commented on docs/source/solution/database.rst
> +      "username": "Foo Bar",
So that we can drop the `user-id` thing *and* allow permalink to user profile, mention and similar thing.

2020-11-15 13:26 UTC, Huy-Ngo commented on docs/source/solution/database.rst
> +      "username": "Foo Bar",
I see. However, it is recommended against that the id of the object has any meaning other something for the system to index, so let's create another field just for the system to read.

2020-11-15 13:27 UTC, Huy-Ngo commented
Lacking: metadata for things. @9a24f0 As I was reviewing your PR, I realized metadata like deadlines for tasks and projects are lacking. Can you have some input into this?

2020-11-15 16:53 UTC, 9a24f0 commented on docs/source/solution/database.rst
> +      "name": "task name",
I think we should include "description" in this.

2020-11-16 03:49 UTC, Huy-Ngo commented
Any other addition? @9a24f0

2020-11-16 04:00 UTC, McSinyx commented on docs/source/solution/database.rst
> +      "username": "very_unique_username"
One identifier is enough I suppose

```suggestion
      "username": "very_unique_username",
```

JSON specs doesn't allow comments like but not like I give a damn since this is just to note the structure.

2020-11-16 07:00 UTC, DDHLong commented on docs/source/solution/database.rst
> +      "username": "very_unique_username"
In case the username can be changed, I suggest we keep the id

2020-11-16 07:37 UTC, McSinyx commented
Fix the missing comma and we're good to go!

2020-11-16 07:46 UTC, McSinyx approved these changes
LGTM!

2020-11-16 08:08 UTC, 9a24f0 commented
> Any other addition? @9a24f0

As for this iteration, LGTM!

2020-11-16 08:08 UTC, 9a24f0 approved these changes

2020-11-16 08:16 UTC, merged