Start documenting impl mechanisms
Huy-Ngo/gpms pull request #14
Opened 2020-11-13 08:27 UTC by McSinyx

Highly WIP, gonna finalize once I get home.

2020-11-15 07:37 UTC, McSinyx commented
[Sorry 4 the Wait](https://en.wikipedia.org/wiki/Sorry_4_the_Wait), it's ready for review now.

2020-11-15 13:35 UTC, Huy-Ngo commented on docs/source/architecture/mechanisms.rst
> +==================  ==========================  ========================
I think there could be some more mechanisms:

- Error Management: Allows errors to be detected, propagated, and reported.
- Security: Provides services to protect access to certain resources or information

Though probably we should not, for now. Also, I'm not too familiar with the deployment of RethinkDB and IPFS, maybe you can help me? The deadline is near.

2020-11-15 13:37 UTC, Huy-Ngo commented
Is this relevant to Dr Quang's task about "business layer"?

2020-11-15 14:23 UTC, McSinyx commented on docs/source/architecture/mechanisms.rst
> +==================  ==========================  ========================
Error management should be part of Python and the libraries, I'm not sure *how* to describe it.  Security should be handled by GH-6 I think.

I installed IPFS using [ipfs-update](https://github.com/ipfs/ipfs-update), but I suppose we can choose a distro whose repo includes IPFS.  [This is the systemd service I use.](https://git.sr.ht/~cnx/dotfiles/tree/master/debian/.config/systemd/user/ipfs.service)

For RethinkDB, I have no experience either, but [there's a quite detailed setup guide on their page](https://rethinkdb.com/docs/start-on-startup/).

2020-11-15 14:29 UTC, McSinyx commented
IIRC business layer refers to the modules implementing [business logic](https://en.wikipedia.org/wiki/Business_logic) and thus deals with common issue specific to such business/field.  Since we can (and should?) defer most common stuff to 3rd party libraries, I *think* what needs to be done is to find the right ones *and* use them right.  If I interpret Dr Quang right, he meant to let us dig one potential issues and have a good overview of the system-to-be, but I'm not exactly sure.

2020-11-15 14:42 UTC, Huy-Ngo commented on docs/source/architecture/mechanisms.rst
> +==================  ==========================  ========================
I took a look at [IPFS Installation section](https://docs.ipfs.io/install/command-line/#package-managers) and they say install from snap, from packaged binary, or build from source?

2020-11-15 14:44 UTC, Huy-Ngo requested changes
Besides these small grammar mistakes, I think it's good to go.

2020-11-15 14:44 UTC, Huy-Ngo commented on docs/source/architecture/mechanisms.rst
> +   A means to make an element persistent,
A mean*

2020-11-15 14:44 UTC, Huy-Ngo commented on docs/source/architecture/mechanisms.rst
> +   i.e. exist after the application that created it ceases to exist.
Should be *exists.

2020-11-15 15:36 UTC, McSinyx commented on docs/source/architecture/mechanisms.rst
> +==================  ==========================  ========================
Use `ipfs-update` (which is basically a program that unpack prebuilt binaries to your GOPATH, because go-ipfs can no longer be `get`), it's the sanest option if your distro doesn't provide go-ipfs.

2020-11-15 15:38 UTC, McSinyx commented on docs/source/architecture/mechanisms.rst
> +   A means to make an element persistent,
Thanks, addressed in a3c1561.

2020-11-15 15:38 UTC, McSinyx commented on docs/source/architecture/mechanisms.rst
> +   i.e. exist after the application that created it ceases to exist.
Thanks, addressed in a3c1561.

2020-11-15 23:56 UTC, Huy-Ngo approved these changes
LGTM

2020-11-16 15:04 UTC, DDHLong approved these changes

2020-11-17 02:31 UTC, merged